name: bazel build

on:
  push
  
jobs:
  bazel_build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3 
        - uses: bazelbuild/setup-bazelisk@v2
        - name: Mount bazel cache  # Optional
          uses: actions/cache@v3
          with:
            path: "~/.cache/bazel"
            key: bazel
        - run: bazel build //...
        - run: bazel run //third_party:requirements.update
        - run: cp $(bazel info output_base)/external/rules_snyk_pip_deps/requirements.bzl third_party/py_requirements.bzl
        - name: Commit changes
          uses: EndBug/add-and-commit@v8
          with:
            default_author: github_action
            message: 'update vendored python requirements file'
            add: 'third_party/py_requirements.bzl'
